package com.example

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // IntroScreen
    val awakenMagic: String = "ĐÁNH THỨC SỨC MẠNH",
    val igniteJourney: String = "BẮT ĐẦU HÀNH TRÌNH",
    val introTitle1: String = "Học Tập Thông Minh",
    val introDesc1: String = "Khám phá chân trời kiến thức mới với AI",
    val introTitle2: String = "Lộ Trình Cá Nhân",
    val introDesc2: String = "Hệ thống tự động điều chỉnh theo trình độ của bạn",
    val introTitle3: String = "Giải Bài Siêu Tốc",
    val introDesc3: String = "Chụp ảnh bài tập và nhận lời giải chi tiết",
    val getStarted: String = "Bắt Đầu",
    val skip: String = "Bỏ Qua",
    
    // IdentitySelectionScreen
    val selectRealm: String = "Chọn Cấp Độ",
    val middleSchool: String = "Cấp 2",
    val highSchool: String = "Cấp 3",
    val university: String = "Đại Học / Cao Đẳng",
    val chooseDiscipline: String = "Chọn Môn Học",
    val webDev: String = "Lập trình Web",
    val advMath: String = "Toán Cao Cấp",
    val physicsChem: String = "Vật Lý & Hóa Học",
    val profileInitialized: String = "Hồ Sơ Đã Sẵn Sàng",
    val profileReady: String = "Hồ sơ năng lực của bạn đã sẵn sàng. Hãy đánh thức sức mạnh ngay!",
    val enterMap: String = "VÀO BẢN ĐỒ",
    // Auth
    val emailMustEndWithGmail: String = "Email phải có đuôi @gmail.com",
    val emailExists: String = "Email đã tồn tại!",
    val regSuccess: String = "Đăng ký thành công!",
    val passwordReq: String = "Mật khẩu: 8 ký tự, 1 hoa, 1 thường, 1 số!",
    val incorrectLogin: String = "Sai email hoặc mật khẩu!",
    val kikiQuote: String = "\"Hành trình vạn dặm tri thức bắt đầu từ một lần định danh.\" — Kiki",
    val createAccount: String = "Tạo Tài Khoản",
    val welcomeBack: String = "Chào Mừng Trở Lại",
    val fullName: String = "Họ và Tên",
    val emailAddress: String = "Địa chỉ Email",
    val passwordLabel: String = "Mật khẩu",
    val signUp: String = "Đăng Ký",
    val login: String = "Đăng Nhập",
    val alreadyHaveAccount: String = "Đã có tài khoản? Đăng nhập",
    val dontHaveAccount: String = "Chưa có tài khoản? Đăng ký",
    // MainMapScreen
    val noChaptersFound: String = "Không tìm thấy chương nào cho cấp độ của bạn. Vui lòng thử lại!",
    val manaLabel: String = "MANA",
    // RankRevealScreen
    val destinyRevealed: String = "ĐỊNH MỆNH ĐÃ HÉ LỘ!",
    val crystalKnight: String = "Hiệp Sĩ\nPha Lê",
    val levelAchieved: String = "Đạt cấp độ B1. Bạn đã mở khóa vùng đất Anthill.",
    val startingManaAwarded: String = "Nhận +500 Mana khởi điểm!",
    val checkAIAnalysis: String = "XEM PHÂN TÍCH AI",
    val continueJourney: String = "TIẾP TỤC HÀNH TRÌNH",
    val levelLabel: String = "CẤP ĐỘ",
    val subjectLabel: String = "MÔN HỌC",
    val beginJourney: String = "Bắt đầu hành trình",
    val selectAll: String = "Hãy chọn đủ cấp độ và môn học",
    
    // MainMapScreen & ProgressionMapScreen
    val levelPrefix: String = "Cấp: ",
    val tapToContinue: String = "Chạm để tiếp tục",
    val chapterPrefix: String = "Chương ",
    val dailyQuests: String = "Nhiệm Vụ Ngày",
    val dailyChest: String = "Rương Ngày",
    val openChestFull: String = "Mở để nhận thưởng!",
    val openChestEmpty: String = "Hoàn thành nhiệm vụ để mở",
    val rewardClaimed: String = "Đã nhận thưởng!",
    val claim: String = "NHẬN",
    val noActiveQuests: String = "Không có nhiệm vụ nào hôm nay",
    val chestOpenedMsg: String = "Đã mở rương! +500 XP",
    
    // QuestScreen
    val manaLevel: String = "NĂNG LƯỢNG",
    val questPrefix: String = "THỬ THÁCH #",
    val castSpell: String = "TRẢ LỜI",
    val skipQuest: String = "BỎ QUA",
    val life: String = "MẠNG",
    val loading: String = "Đang tải...",
    
    // QuestReviewScreen
    val historyAnalysis: String = "Lịch Sử & Phân Tích",
    val aiMentorInsight: String = "Phân Tích Từ Cố Vấn AI",
    val analyzing: String = "Kiki đang phân tích lỗi sai...",
    val analysisComplete: String = "Phân tích hoàn tất",
    val questionDetails: String = "Chi tiết câu hỏi",
    val questionLabel: String = "Câu hỏi ",
    val youChose: String = "Bạn chọn: ",
    val correctAnswer: String = "Đáp án đúng: ",
    val skipped: String = "Đã bỏ qua",
    val errorString: String = "Lỗi",
    val gradeS: String = "Tuyệt vời! Bạn là thiên tài!",
    val gradeA: String = "Làm tốt lắm! Tiếp tục phát huy!",
    val gradeB: String = "Nỗ lực tốt! Hãy cải thiện thêm!",
    val gradeC: String = "Đừng bỏ cuộc! Hãy xem lại bên dưới.",
    
    // QuestsScreen
    val quest1Title: String = "Học Khoa Học",
    val quest1Desc: String = "Hoàn thành 1 bài học Khoa học",
    val quest2Title: String = "Điểm Tuyệt Đối",
    val quest2Desc: String = "Đạt 100% trong bất kỳ bài học nào",
    val quest3Title: String = "Người Tìm Tri Thức",
    val quest3Desc: String = "Trả lời 10 câu hỏi",
    val chestOpenedToast: String = "Đã mở rương! +500 XP",
    val tapChest: String = "Chạm để nhận thưởng lớn!",
    val completeAllToOpen: String = "Hoàn thành tất cả để mở",
    
    // AskScreen
    val knowledgeDecoder: String = "Giải Mã Tri Thức",
    val attachedImage: String = "Ảnh đính kèm",
    val kikiAnalyzingSocratic: String = "Kiki đang phân tích (Socratic):",
    val moreExplanation: String = "Giải thích thêm",
    val similarProblems: String = "Bài tập tương tự",
    val kikiDecodingMagic: String = "Kiki đang giải mã phép thuật",
    val summonMagic: String = "Triệu Hồi Phép Thuật",
    val summonMagicDesc: String = "Nhập câu hỏi hoặc chụp ảnh sách ma thuật để Cố Vấn AI giúp bạn giải mã ngay lập tức!",
    val castingQuestion: String = "Đang đặt câu hỏi...",
    
    // RankScreen
    val rankedArena: String = "Đấu Trường Xếp Hạng",
    val noRankings: String = "Chưa có bảng xếp hạng. Hãy bắt đầu học để leo bảng xếp hạng!",
    val unranked: String = "Chưa xếp hạng",
    val unknown: String = "Không xác định",
    
    // ProfileScreen
    val settingsTitle: String = "Cài Đặt",
    val languageLabel: String = "Ngôn Ngữ (Language)",
    val langCurrent: String = "Tiếng Việt",
    val logout: String = "Đăng Xuất",
    val notifications: String = "Thông báo",
    val soundEffects: String = "Hiệu ứng âm thanh",
    
    // AskScreen
    val askMentor: String = "Hỏi Gia Sư Kiki",
    val typeQuestion: String = "Nhập câu hỏi của bạn...",
    val thinking: String = "Kiki đang suy nghĩ...",
    
    // RankScreen
    val leaderboard: String = "Bảng Vàng",
    val rank: String = "Hạng",
    val xpLabel: String = "XP",
    val today: String = "Hôm nay",
    val thisWeek: String = "Tuần này",
    val allTime: String = "Tất cả",
    
    // Misc
    val menuLabel: String = "Mở menu",
    val menuTitle: String = "Điều hướng",
    val menuMap: String = "Bản đồ học",
    val menuQuests: String = "Nhiệm vụ hằng ngày",
    val menuAsk: String = "Hỏi gia sư Kiki",
    val menuRank: String = "Xếp hạng",
    val menuProfile: String = "Hồ sơ cá nhân",
    val menuSettings: String = "Cài đặt",
    val menuLogout: String = "Đăng xuất",
    val learningProgress: String = "Tiến độ học",
    val lessonProgress: String = "Bài {current}/{total}",
    val mapCompleted: String = "Đã hoàn thành bản đồ",
    val viewStats: String = "Xem thống kê",
    val rewardLocked: String = "Hoàn thành tất cả chặng để mở phần thưởng đặc biệt.",
    val rewardUnlocked: String = "Rương phần thưởng đã mở khóa!",
    val openReward: String = "XEM PHẦN THƯỞNG",
    val starsLabel: String = "SAO",
    val navMap: String = "Bản đồ",
    val navLearn: String = "Học",
    val navTutor: String = "Gia sư",
    val navRank: String = "Xếp hạng",
    val navProfile: String = "Hồ sơ",
    val journeyEmptyTitle: String = "Hành trình sẵn sàng bắt đầu",
    val journeyEmptyDescription: String = "Hãy chọn môn học hoặc bắt đầu bài học đầu tiên để tạo lộ trình của bạn.",
    val retry: String = "Thử lại",
    val mapTitle: String = "BẢN ĐỒ HÀNH TRÌNH",
    val mapSubtitle: String = "Mỗi bài học là một bước tiến mới",
    val chapterCompleted: String = "Đã hoàn thành",
    val chapterCurrent: String = "Đang học",
    val chapterLocked: String = "Đang khóa",
    val unlockAfterChapter: String = "Hoàn thành chương trước để mở khóa",
    val yes: String = "Có",
    val no: String = "Không"
)

val VietnameseStrings = AppStrings()

val EnglishStrings = AppStrings(
    awakenMagic = "AWAKEN YOUR MAGIC",
    igniteJourney = "IGNITE JOURNEY",
    introTitle1 = "Smart Learning",
    introDesc1 = "Discover new horizons of knowledge with AI",
    introTitle2 = "Personalized Path",
    introDesc2 = "The system automatically adjusts to your level",
    introTitle3 = "Lightning Fast Solutions",
    introDesc3 = "Snap a photo and get detailed explanations",
    getStarted = "Get Started",
    skip = "Skip",
    
    selectRealm = "Select your Realm",
    middleSchool = "Middle School",
    highSchool = "High School",
    university = "University / College",
    chooseDiscipline = "Choose Discipline",
    webDev = "Web Development",
    advMath = "Advanced Mathematics",
    physicsChem = "Physics & Chemistry",
    profileInitialized = "Profile Initialized",
    profileReady = "Your competency profile is ready. Awaken your power now!",
    enterMap = "ENTER MAP",
    
    emailMustEndWithGmail = "Email must end with @gmail.com",
    emailExists = "Email already exists!",
    regSuccess = "Registration successful!",
    passwordReq = "Password: 8 chars, 1 upper, 1 lower, 1 digit!",
    incorrectLogin = "Incorrect email or password!",
    kikiQuote = "\"Your journey of a thousand words begins with a single identification.\" — Kiki",
    createAccount = "Create Account",
    welcomeBack = "Welcome Back",
    fullName = "Full Name",
    emailAddress = "Email Address",
    passwordLabel = "Password",
    signUp = "Sign Up",
    login = "Login",
    alreadyHaveAccount = "Already have an account? Login",
    dontHaveAccount = "Don't have an account? Sign Up",
    
    noChaptersFound = "No chapters found for your level. Try another preference!",
    manaLabel = "MANA",
    destinyRevealed = "DESTINY REVEALED!",
    crystalKnight = "Crystal\nKnight",
    levelAchieved = "Level B1 Achieved. You have unlocked the Anthill Realm.",
    startingManaAwarded = "+500 Starting Mana awarded!",
    checkAIAnalysis = "CHECK AI ANALYSIS",
    continueJourney = "CONTINUE JOURNEY",
    
    levelLabel = "LEVEL",
    subjectLabel = "SUBJECT",
    beginJourney = "Begin Journey",
    selectAll = "Please select both level and subject",
    
    levelPrefix = "Level: ",
    tapToContinue = "Tap to continue",
    chapterPrefix = "Chapter ",
    dailyQuests = "Daily Quests",
    dailyChest = "Daily Chest",
    openChestFull = "Tap to open!",
    openChestEmpty = "Complete all to open",
    rewardClaimed = "Reward Claimed!",
    claim = "CLAIM",
    noActiveQuests = "No active quests today",
    chestOpenedMsg = "Chest opened! +500 XP",
    
    manaLevel = "MANA LEVEL",
    questPrefix = "QUEST #",
    castSpell = "CAST SPELL",
    skipQuest = "SKIP QUEST",
    life = "LIFE",
    loading = "Loading...",
    
    historyAnalysis = "History & Analysis",
    aiMentorInsight = "AI Mentor Insight",
    analyzing = "Kiki is analyzing your mistakes...",
    analysisComplete = "Analysis Complete",
    questionDetails = "Question Details",
    questionLabel = "Question ",
    youChose = "You chose: ",
    correctAnswer = "Correct answer: ",
    skipped = "Skipped",
    errorString = "Error",
    gradeS = "Perfect Mastery! You're a genius!",
    gradeA = "Great Job! Keep it up!",
    gradeB = "Good effort! Let's improve!",
    gradeC = "Don't give up! Review below.",
    
    quest1Title = "Study Science",
    quest1Desc = "Complete 1 Science lesson",
    quest2Title = "Perfect Score",
    quest2Desc = "Get 100% in any lesson",
    quest3Title = "Knowledge Seeker",
    quest3Desc = "Answer 10 questions",
    chestOpenedToast = "Chest Opened! +500 XP",
    tapChest = "Tap chest for big rewards!",
    completeAllToOpen = "Complete all to open",
    
    knowledgeDecoder = "Knowledge Decoder",
    attachedImage = "Attached image",
    kikiAnalyzingSocratic = "Kiki is analyzing (Socratic):",
    moreExplanation = "More explanation",
    similarProblems = "Similar problems",
    kikiDecodingMagic = "Kiki is decoding magic",
    summonMagic = "Summon Magic",
    summonMagicDesc = "Enter a problem or take a photo of a magic book so AI Mentor can help you decode it instantly!",
    castingQuestion = "Casting question...",
    
    rankedArena = "Ranked Arena",
    noRankings = "No rankings available yet. Start learning to climb the leaderboard!",
    unranked = "Unranked",
    unknown = "Unknown",
    
    settingsTitle = "Settings",
    languageLabel = "Language (Ngôn Ngữ)",
    langCurrent = "English",
    logout = "Logout",
    notifications = "Notifications",
    soundEffects = "Sound Effects",
    
    askMentor = "Ask Mentor Kiki",
    typeQuestion = "Type your question...",
    thinking = "Kiki is thinking...",
    
    leaderboard = "Hall of Fame",
    rank = "Rank",
    xpLabel = "XP",
    today = "Today",
    thisWeek = "This Week",
    allTime = "All Time",

    menuLabel = "Open menu",
    menuTitle = "Navigation",
    menuMap = "Learning map",
    menuQuests = "Daily quests",
    menuAsk = "Ask Kiki",
    menuRank = "Leaderboard",
    menuProfile = "Profile",
    menuSettings = "Settings",
    menuLogout = "Log out",
    learningProgress = "Learning progress",
    lessonProgress = "Lesson {current}/{total}",
    mapCompleted = "Learning map completed",
    viewStats = "View stats",
    rewardLocked = "Complete all stages to unlock your special reward.",
    rewardUnlocked = "Your special reward is unlocked!",
    openReward = "VIEW REWARD",
    starsLabel = "STARS",
    navMap = "Map",
    navLearn = "Learn",
    navTutor = "Tutor",
    navRank = "Rank",
    navProfile = "Profile",
    journeyEmptyTitle = "Your journey is ready to begin",
    journeyEmptyDescription = "Choose a subject or start your first lesson to create your learning path.",
    retry = "Retry",
    mapTitle = "LEARNING JOURNEY",
    mapSubtitle = "Every lesson is a step forward",
    chapterCompleted = "Completed",
    chapterCurrent = "In progress",
    chapterLocked = "Locked",
    unlockAfterChapter = "Complete the previous chapter to unlock",
    
    yes = "Yes",
    no = "No"
)

val LocalAppStrings = staticCompositionLocalOf { VietnameseStrings }
